name: Compile

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: xmake-io/github-action-setup-xmake@v1
      - uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      - name: Build
        run: |
          xmake
      - name: Zip
        run: |
          zip -r divine-linux-x86_64.zip ./build/linux/x86_64/release/
      - name: Publish
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: push-$GIT_TAG_NAME-linux
          files: |
            divine-linux-x86_64.zip
